<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="..\Mono.Cecil.Tests.props" />
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.1;net40</TargetFrameworks>
    <AssemblyName>Mono.CecilX.Tests</AssemblyName>
    <RootNamespace>Mono.CecilX.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp">
      <Version>2.10.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mono.Cecil.csproj">
      <Name>Mono.CecilX</Name>
    </ProjectReference>
    <ProjectReference Include="..\symbols\mdb\Mono.Cecil.Mdb.csproj">
      <Name>Mono.CecilX.Mdb</Name>
    </ProjectReference>
    <ProjectReference Include="..\symbols\pdb\Mono.Cecil.Pdb.csproj">
      <Name>Mono.CecilX.Pdb</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ProjectInfo.cs" />
    <Compile Include="Mono.Cecil.Tests\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\**\*" />
  </ItemGroup>
</Project>
