<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net40</TargetFrameworks>
    <DefineConstants>$(DefineConstants);INSIDE_ROCKS</DefineConstants>
    <AssemblyName>Mono.CecilX.Rocks</AssemblyName>
    <RootNamespace>Mono.CecilX.Rocks</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mono.Cecil.csproj">
      <Name>Mono.CecilX</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ProjectInfo.cs" />
    <Compile Include="Mono.Cecil.Rocks\*.cs" />
  </ItemGroup>
</Project>